

services:
  frontend:
    image: frontend-image:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  backend:
    image: backend-image:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/MERN-Notes-App
      - JWT_SECRET=H#7gL!qZ$39p@tD1vEw&kNmZ^PzLuQsXaT!gBcD^r
    depends_on:
      - mongo
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

volumes:
  mongo_data:

networks:
  app-network:
    driver: overlay
